### ISSUE TITLE
Invalid Params with example code.

### ISSUE THREAD

**Issue by tomgie** [freewil/node-bitcoin#34]
I run the example code with no ssl and I get this error. 

{ Error: Invalid params, response status code: 401
    at IncomingMessage.<anonymous> (/root/bitcoin/node_modules/bitcoin/lib/jsonrpc.js:110:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: -32602 }

**Comment by patrickmedaugh** [comment]
You may have to configure your bitcoind. My bitcoind looks for bitcoin.conf in Library/Application Support/Bitcoin, so I made a bitcoin.conf file there and set rpcuser and rpcpass in that file and got it working.
